### ISSUE TITLE
January Movie Night

### ISSUE THREAD

**Issue by frogcrush** [trusuanimeclub/Planning#1]
Confirmed for 26 January, doors open at 6:30, movie starts at 7. People are invited to bring blankets and pillows. 

TODO:

- [x] Find room/venue
- [x] Decide on movie
- [x] Design Posters
- [x] Contact advertising people

ADVERTISING TODO:
- [ ] Banner image for Old Main (34 or 44 inches x whatever, prolly make it a 16x9 rectangle?)
- [ ] General poster - either legal or letter size (8 1/2 x 11" or 8 1/2 x 14")
- [ ] Make image for monitors around campus (1920x1080 pixels)

Images should be made at that full size; we can always shrink them down if necessary.

**Comment by frogcrush** [comment]
So far we've watched: 
Princess Mononoke
Howl's Moving Castle
5 Centimeter Per Second

**Comment by frogcrush** [comment]
Kimi no na wa is the suggested movie and we might be able to snag the TRUSU board room.

**Comment by frogcrush** [comment]
TRUSU Board Room is pending a booking.

**Comment by frogcrush** [comment]
Sizing for posters:
8 1/2 x 11" OR 8 1/2 x 14"
Screen:
1920x1080 pixels, <1 MB file size (final) >> http://trusu.ca/campus-life/clubs/advertising/

**Comment by frogcrush** [comment]
We can also have a banner printed and hung in Old Main:

https://www.tru.ca/forms/marcom/streetbanners/
http://trusu.ca/campus-life/clubs/printing/

See those sites for sizing.

**Comment by Abhi-wan-kenobhi** [comment]
Which size banner do we wanna do? 44" might be too big for the info we're gonna put on it.

**Comment by frogcrush** [comment]
Well we want it to be big so people can see it, right? We could prolly take a vector of the one for a normal size piece of paper and blow it up to whatever size. Like, layout/sizing/scaling wise. Since it's on a wall

**Comment by frogcrush** [comment]
I think that, like with our last poster, we should include links to our Facebook, Discord, and website on the poster as well.

**Comment by hexadecatrienoic** [comment]
Can you leave the links here?

**Comment by frogcrush** [comment]
For which?

**Comment by hexadecatrienoic** [comment]
#6 - ready to go up whenever
