### ISSUE TITLE
Fall 2018 First Movie Night

### ISSUE THREAD

**Issue by frogcrush** [trusuanimeclub/Planning#12]
Tasks:

- [x] Book room
- [x] Update website
- [x] Book banner space
- [x] Design posters
- [x] Design banner
- [x] Have posters printed
- [x] Have banner printed
- [x] Hang posters
- [x] Hang banner

First movie night was decided to be Akira on 28 September 2018.

**Comment by napcolors** [comment]
First Event Survey!
Tasks

- [x] Review survey below

- [x] Get the design people to make Survey look nice pls

- [x] print out ~40? or however many estimated for movie event

- [x] hand out at event

- [ ] make digital survey for discord only members

- [ ] use results to plan future events

[TRUSU ANIME CLUB SURVEY.docx](https://github.com/trusuanimeclub/Planning/files/2414472/TRUSU.ANIME.CLUB.SURVEY.docx)

**Comment by napcolors** [comment]
maybe add a "Any movie suggestions?" section to the survey too

**Comment by napcolors** [comment]
revised survey
[TRUSU ANIME CLUB SURVEY (1) revised.docx](https://github.com/trusuanimeclub/Planning/files/2421905/TRUSU.ANIME.CLUB.SURVEY.1.revised.docx)

**Comment by UltimatePanzerMaiden** [comment]
[WEEBCLUBSURVEY_UPM_REVISIONS.docx](https://github.com/trusuanimeclub/Planning/files/2422016/WEEBCLUBSURVEY_UPM_REVISIONS.docx)

**Comment by Abhi-wan-kenobhi** [comment]
I'm fine with Tylor's revision of it. I don't mind the idea of asking for their preferred genre but I think asking for a movie suggestion would be more than enough to figure that out. If we're gonna have it there, I'd reduce the field for it to one line. Other than that, I don't have any issues with it as long as the font look okay.

**Comment by UltimatePanzerMaiden** [comment]
Adding the logo is probs something we should do. That's pretty important. That and a simple thank you of course.

**Comment by Abhi-wan-kenobhi** [comment]
I'm fine with either way since it's just a B&W survey.

**Comment by UltimatePanzerMaiden** [comment]
[WEEBCLUBSURVEY_UPM_REVISIONS.docx](https://github.com/trusuanimeclub/Planning/files/2422059/WEEBCLUBSURVEY_UPM_REVISIONS.docx)
Added the logo. Double check how it looks before a mass batch, if it's used

**Comment by frogcrush** [comment]
[Club Survey Paper Fall 2018.docx](https://github.com/trusuanimeclub/Planning/files/2422061/Club.Survey.Paper.Fall.2018.docx)

**Comment by frogcrush** [comment]
We need the logo on my version and we should be good

**Comment by frogcrush** [comment]
[Club Survey Paper Fall 2018.docx](https://github.com/trusuanimeclub/Planning/files/2422083/Club.Survey.Paper.Fall.2018.docx)
(final version)

**Comment by frogcrush** [comment]
[Club Survey Paper Fall 2018.docx](https://github.com/trusuanimeclub/Planning/files/2422091/Club.Survey.Paper.Fall.2018.docx)
(final version)

**Comment by Abhi-wan-kenobhi** [comment]
I would cut off some space between the logo and the title but it's not a bother so I'll go with it. <3

**Comment by Abhi-wan-kenobhi** [comment]
Ticked off the first two tasks in charlie's post above.

**Comment by frogcrush** [comment]
[Club Survey Paper Fall 2018.docx](https://github.com/trusuanimeclub/Planning/files/2422147/Club.Survey.Paper.Fall.2018.docx)
(final final)

**Comment by napcolors** [comment]
[TRUSU.anime.club.surevey.fusion.docx](https://github.com/trusuanimeclub/Planning/files/2422165/TRUSU.anime.club.surevey.fusion.docx)
a compromise?
