### ISSUE TITLE
Cosplay Competition

### ISSUE THREAD

**Issue by frogcrush** [trusuanimeclub/Planning#2]
TODO:

- [ ] Decide on date (thinking March)
- [ ] Find a location/room
- [ ] Advertise advertise advertise

QUESTIONS:
Should people RSVP? That way we can get general numbers for the competition (and for guests)

**Comment by frogcrush** [comment]
A more lax runway-type event was suggested in Discord; this way people aren't rushing to prep. We could have a more formal competition in the new semester if we wanted.

**Comment by Abhi-wan-kenobhi** [comment]
Bumping this 'cuz we might wanna look into doing this. Recently talked to Cara Cadre who teaches Japanese and she suggested we should do this, and there actually are a decent amount of people who'd be into it.

- [ ] get feedback from discord (optional)

- [ ] decide if wanna do just a casual one, or a competition event

- [ ] See if we can book one of the big rooms in CAC building (https://www.tru.ca/cac/facilities-venues/)

- [ ] Decide a date so we can apply for a grant (need some kind of prize if we're doing a competitive - https://trusu.ca/grants/deadlines/)

- [ ] decide prize and things we'll need on the event day

- [ ] advertise hard
