### ISSUE TITLE
February 2018 Movie Night

### ISSUE THREAD

**Issue by frogcrush** [trusuanimeclub/Planning#7]
- [x] Send survey for best night & what movie
- [ ] Design posters
- [ ] Book room
- [ ] Advertise

**Comment by frogcrush** [comment]
Proposed movies (so far):

- Kono Sekai no Katasumi ni (In This Corner of the World) https://myanimelist.net/anime/15227/Kono_Sekai_no_Katasumi_ni
- Koe no Katachi (A Silent Voice) https://myanimelist.net/anime/28851/Koe_no_Katachi
- Toki o Kakeru Shojo (The Girl Who Leapt Through Time) https://myanimelist.net/anime/2236/Toki_wo_Kakeru_Shoujo
- Ookami Kodomo no Ame to Yuki (Wolf Children) https://myanimelist.net/anime/12355/Ookami_Kodomo_no_Ame_to_Yuki
- ~~Akira (Akira) https://myanimelist.net/anime/47/Akira~~
- Tonari no Totoro (My Neighbor Totoro) https://myanimelist.net/anime/523/Tonari_no_Totoro
- ~~Girls und Panzer der Film~~ (requires knowledge of the series)
- Ghost in the Shell (Ghost in the Shell) https://myanimelist.net/anime/43/Ghost_in_the_Shell
- ~~Sword Art Online the Movie: Ordinal Scale~~ (requires knowledge of the books)
- ~~Strike Witches Movie~~ (requires knowledge of the series)

**Comment by kreh** [comment]
+1 Akira

I can design posters if need be

**Comment by Abhi-wan-kenobhi** [comment]
Add Paprika to the list, It's another good movie.

**Comment by frogcrush** [comment]
no

**Comment by Abhi-wan-kenobhi** [comment]
Why not?

**Comment by frogcrush** [comment]
cuz we don't need to scar the highschoolers

**Comment by Abhi-wan-kenobhi** [comment]
Then might as well remove Akira, 'cuz they're basically the same kind of movies.

**Comment by frogcrush** [comment]
done

**Comment by kreh** [comment]
what was the consensus?
